id: P003037
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:35:55.992499
source_metadata:
  id: bdr:W1KG3537
  title: པདྨ་དབང་ཆེན་བསྟན་འཛིན་ཕྲིན་ལས་ཀྱི་རྟོགས་བརྗོད་
  author: ''
  volumes:
    2c4a7cba86e5410f9688b67c1e11509a:
      image_group_id: I1KG3606
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
